steps:
  - name: ubuntu
    args:
      - '-c'
      - echo $$_ACTION
      - echo $_PRNUMBER
    id: echo
    entrypoint: bash
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       echo "###############################"
       echo $_ACTION
       echo "###############################"
       echo "###############################"
       echo $_CHANGED_FILES2
       echo "###############################"
       echo "###############################"
       echo $_CHANGED_FILES1
       echo "###############################"
       echo "###############################"
       echo $_CHANGED_FILES
       echo "###############################"
       echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
       apt update && apt install -y gh
       gh --version

       echo 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 >> ./token
       ls -al
       
  - name: ghcr.io/supportpal/github-gh-cli
    args:
      - |
        echo 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 | gh auth login --with-token
    id: pubsub
    entrypoint: bash
    
  - name: ghcr.io/supportpal/github-gh-cli
    args: ['pr','diff','18']
    id: pr
    entrypoint: gh

  - name: ghcr.io/supportpal/github-gh-cli
    args: ['cat','./token']
    id: cat
    entrypoint: /bin/bash
    
logsBucket: 'gs://proud-gate-400110-logging'
substitutions:
  _ACTION: $(body.action)
  _PRNUMBER: $(body.number)
  _SHNUM: $(body.pull_request.head.sha)
  _CHANGED_FILES: $(body.pull_request.changed_files)
 
options:
  substitution_option: ALLOW_LOOSE



