steps:
  - name: ubuntu
    args:
      - '-c'
      - echo $body
      - body=$1
      - echo $body
      - echo $_REGION
    id: echo
    entrypoint: bash
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       echo "GitHub Webhook Payload:"
       echo $PROJECT_ID
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   args:
  #     - pubsub
  #     - topics
  #     - publish
  #     - my-pubsub-topic
  #     - '--message="hello"'
  #   id: pubsub
  #   entrypoint: gcloud
    
logsBucket: 'gs://proud-gate-400110-logging'
substitutions:
  _REGION: $(body)

options:
  substitution_option: ALLOW_LOOSE

