steps:
  - name: ubuntu
    args:
      - '-c'
      - |
        echo "###############################"
        echo $_ACTION
        echo
        ls -la
        echo "###############################"
        echo "export NEW_PR=$(echo $$PR_NUM)" >> /workspace/env.sh
        echo "export NEW_PRRRR=$(echo $_PRNUMBER)" >> /workspace/env.sh
        cat 
    id: echo
    entrypoint: bash
    
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp','gs://gcf-v2-uploads-227553364515-europe-west1/token','.']
    id: token
    entrypoint: gsutil
    
    
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       source /workspace/env.sh
       cat workspace/env.sh
       env
       ./scripts/check.sh
    
  - name: gcr.io/proud-gate-400110/gh:1
    args:
     - '-c'
     - |
       echo "###############################"
       gh --version
       echo "###############################"
       echo AUTHENTICATING
       cat token | gh auth login --with-token
       git diff
       echo "###############################"
       echo "Hello gi diff"
    id: pr

    
logsBucket: 'gs://proud-gate-400110-logging'
substitutions:
  _ACTION: $(body.action)
  _PRNUMBER: $(body.number)
  _SHNUM: $(body.pull_request.head.sha)
  _CHANGED_FILES: $(body.pull_request.changed_files)

 
options:
  substitution_option: ALLOW_LOOSE
  env:
  - PR_NUMBER=$_PRNUMBER



