steps:
  - name: ubuntu
    args:
      - '-c'
      - |
        echo "###############################"
        echo $_ACTION
        echo
        PWD
        ls -la
        echo "###############################"
    id: echo
    entrypoint: bash
    
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp','gs://gcf-v2-uploads-227553364515-europe-west1/token','.']
    id: token
    entrypoint: gsutil
    
    
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       echo "###############################"
       echo $_ADDED
       echo "###############################"
       echo "###############################"
       echo $_MOD
       echo "###############################"
       echo "###############################"
       echo $_REMOVED
       echo "###############################"
       echo "###############################"
       echo $_CHANGED_FILES
       echo "###############################"
       cat token
       ls -al
    
  - name: gcr.io/proud-gate-400110/gh:1
    args:
     - '-c'
     - |
       echo "###############################"
       gh --version
       echo "###############################"
       echo AUTHENTICATING
       cat token | gh auth login --with-token
       gh pr diff $(echo $_PRNUMBER)
       echo "###############################"
    id: pr

    
logsBucket: 'gs://proud-gate-400110-logging'
substitutions:
  _MOD: $(body.head_commit.modified)
  _ADDED: $(body.head_commit.added)
  _REMOVED: $(body.head_commit.removed)
 
options:
  substitution_option: ALLOW_LOOSE
  
