steps:
  - name: ubuntu
    args:
      - '-c'
      - echo $$_ACTION
      - echo $_PRNUMBER
    id: echo
    entrypoint: bash
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       echo "GitHub Webhook Payload:"
       echo $_ACTION
       echo "GitHub Webhook Payload:"
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   args:
  #     - pubsub
  #     - topics
  #     - publish
  #     - my-pubsub-topic
  #     - '--message="hello"'
  #   id: pubsub
  #   entrypoint: gcloud
    
logsBucket: 'gs://proud-gate-400110-logging'
substitutions:
  _ACTION: $(body.action)
  _PRNUMBER: $(body.number)

options:
  substitution_option: ALLOW_LOOSE



