steps:
  - name: ubuntu
    args:
      - '-c'
      - echo $$_ACTION
      - echo $_PRNUMBER
    id: echo
    entrypoint: bash
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       echo "###############################"
       echo $_ACTION
       echo "###############################"
       echo "###############################"
       echo $_CHANGED_FILES2
       echo "###############################"
       echo "###############################"
       echo $_CHANGED_FILES1
       echo "###############################"
       echo "###############################"
       echo $_CHANGED_FILES
       echo "###############################"
       echo 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 >> ./token
       PWD
       ls -al
       
  - name: ghcr.io/supportpal/github-gh-cli
    args: ['auth','login','--with-token','<','./token', '&&', 'gh', 'pr','diff','18']
    id: pubsub
    entrypoint: gh
    
logsBucket: 'gs://proud-gate-400110-logging'
substitutions:
  _ACTION: $(body.action)
  _PRNUMBER: $(body.number)
  _SHNUM: $(body.pull_request.head.sha)
  _CHANGED_FILES: $(body.pull_request.changed_files)
 
options:
  substitution_option: ALLOW_LOOSE



