steps:    
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       echo "###############################"
       echo $_ADDED
       echo "###############################"
       echo "###############################"
       echo $_MOD
       echo "###############################"
       echo "###############################"
       echo $_REMOVED
       echo "###############################"
       echo "###############################"
       echo $_CHANGED_FILES
       echo "###############################"
    
    
logsBucket: 'gs://proud-gate-400110-logging'
substitutions:
  _MOD: $(body.head_commit.modified)
  _ADDED: $(body.head_commit.added)
  _REMOVED: $(body.head_commit.removed)
 
options:
  substitution_option: ALLOW_LOOSE
  
